# Generated by Django 3.1.5 on 2021-01-10 16:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goals", "0003_auto_20210110_1649"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Profile",
        ),
    ]
