# Generated by Django 3.1.5 on 2021-01-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0005_learninggoal_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learninggoal",
            old_name="customer",
            new_name="user",
        ),
    ]
